### ISSUE TITLE
OBS  26.1 Crashing

### ISSUE THREAD

**Issue by PeterAkakpo** [wang-bin/obs-mdk#1]
[obs-mdk crash report.txt](https://github.com/wang-bin/obs-mdk/files/5744203/obs-mdk.crash.report.txt)
Adding a new MDK video source crashes obs. adding a new source with or without OPENGL renderer play the video file with just audio now video and then it crashes
![obs-mdk](https://user-images.githubusercontent.com/7926382/103165961-f234ed00-4815-11eb-926c-893bbaad3726.png)

**Comment by PeterAkakpo** [comment]
seriously no comments? what a shame

**Comment by wang-bin** [comment]
Sorry, there's no notification when an issue created. Try the latest mdk.dll from mdk-sdk project.

**Comment by PeterAkakpo** [comment]
it now working with the latest mdk.dll, thanks
